# GitHub Actions is a popular CI/CD platform for automating your build, test, and deployment pipeline.
# Github Actions are needed to check linting and perform tests 
---
name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04  # OS needed to run your job 
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1 # Docker provides login action to easily login to DockerHub 
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test" 

      - name: Linting 
        run: docker-compose run --rm app sh -c "flake8"